-- print(1 > 0 and 'a' == 'b')
-- print(true or -1 < 8 and (true == 0))
-- print('true' ~= 100 and (10 ~= 10 or 0 == 0) and 'a' < 'b')
-- print((false and true or true) and (10 > 5 and 0 > 1) or ('abc' ~= 'abc'))

print(false or false or true)
print(true and false and true)
print(true or false and true)
print(false or false or false)
print(true and true or true)
print(false and false or false or true)
print(false or true and false and false)
print(true and false or false and true)
print(true and true or false and true or false)
print(false or false and true or true or false and true)
print(false and true or false and false or true and true or false and true and false or true)
print(false or true and false or true and false or false)